version: "3"

services:
  minio:
    image: minio/minio:latest
    container_name: minio_textify
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - "./minio_data:/data"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin123
      - MINIO_DEFAULT_BUCKETS=textify
    restart: always
# WARNING: is not working
